apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  creationTimestamp: null
  name: "5166419876819812678"
  namespace: default
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/emailallau/test444
status: {}
